### ISSUE TITLE
请教一下文章详情右侧的标题栏怎么做到的

### ISSUE THREAD

**Issue by yzbgyq** [gershonv/react-blog#10]
我用的也是mavonEditor，但是我想生成你那种文章右侧的标题，该怎么做
![image](https://user-images.githubusercontent.com/32931212/56200374-3e0b2700-6071-11e9-83a0-34be8644216a.png)

**Comment by gershonv** [comment]
这里用了 antd 的 [Anchor 组件](https://ant.design/components/anchor-cn/)，需要将 article 的 content 转化为所需的格式，具体构建可以看 views/web/article/navigation.jsx 这个组件
