### ISSUE TITLE
js执行顺序

### ISSUE THREAD

**Issue by giserman001** [gershonv/react-blog#17]
![image](https://user-images.githubusercontent.com/24283342/59451130-46979800-8e3d-11e9-8ff2-01f9803d8939.png)

![image](https://user-images.githubusercontent.com/24283342/59451302-bb6ad200-8e3d-11e9-89e8-05d27ff09129.png)

**Comment by giserman001** [comment]
文字写错了

**Comment by giserman001** [comment]
文字写错了

**Comment by gershonv** [comment]
没有返回一个promise…

**Comment by giserman001** [comment]
@gershonv 知道了，谢谢大神
