### ISSUE TITLE
你网站炸了

### ISSUE THREAD

**Issue by cyea** [gershonv/react-blog#6]
![image](https://user-images.githubusercontent.com/22478003/55492091-3444f500-5669-11e9-98e7-4aa28a72a694.png)

**Comment by cyea** [comment]
被 XSS攻击了？

**Comment by cyea** [comment]
![Kapture 2019-04-03 at 23 46 48](https://user-images.githubusercontent.com/22478003/55493086-e630f100-566a-11e9-8bc0-c8ea34f9e339.gif)

**Comment by gershonv** [comment]
是的 通过评论转化 html 注入脚本，所以会跳转。还未 fix，最近比较忙。
已删除相关记录，现可以正常访问

**Comment by cyea** [comment]
嗯 能进去了！

**Comment by gershonv** [comment]
已对 xss 攻击做了处理
