### ISSUE TITLE
小白想请教一下直接运行您的项目时不能请求得到数据该怎么办？

### ISSUE THREAD

**Issue by bbbellC** [gershonv/react-blog#7]

**Comment by Lovate** [comment]
你这是跨域请求不被允许啊，看看你后端的跨域请求策略




| |
周敏文
|
|
邮箱：minwenzhou@163.com
|

签名由 网易邮箱大师 定制

在2019年04月05日 12:47，bbbellC 写道：

像这样子

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:6060/article/getList?page=1&pageSize=6. (Reason: CORS request did not succeed).

该怎么解决？
小白一枚，麻烦指教了。。谢谢

**Comment by gershonv** [comment]
跨域我用的 cors ，应该是没问题的。实在没解决，可以用 proxy

**Comment by Lovate** [comment]
> ，可
你的邮箱是不是填错了，为什么我会收到邮件额
